#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_ftl="0.0.1"
  jq -n --arg ftl "$ver_ftl" '{ftl: $ftl}'
}

version "$@"
